### ISSUE TITLE
non-editable sign

### ISSUE THREAD

**Issue by TheStriker095** [GeyserMC/Geyser#1063]
**Describe the bug**
Unable to place text on lines 2-4 on signs using various versions of Bedrock

**To Reproduce**
On Android or Nintendo Switch (Xbox1, PS4 remain untested)
1. Place a sign
2. Place text on lines 2-4
3. Close GUI
4. Poof, no text on lines 2-4

**Expected behavior**

**Screenshots / Videos**
This warning appears whenever return/enter is pressed while editing a sign:
![image](https://user-images.githubusercontent.com/69020480/88984942-edc6d100-d283-11ea-8d93-f96f5ebc00cf.png)

**Server Version**
![image](https://user-images.githubusercontent.com/69020480/88984965-033bfb00-d284-11ea-89aa-f9b305f8724a.png)

**Geyser Version**
![image](https://user-images.githubusercontent.com/69020480/88985005-1ea70600-d284-11ea-8232-b615b7307ac5.png)

**Minecraft: Bedrock Edition Version**
Android, Nintendo Switch (confirmed not working)
Signs seems to be editable on Win10, iPad.

**Comment by PQguanfang** [comment]
Maybe the problem caused by the plugins installed in your server. I have 2 servers that use Geyser, both of them don't have this problem.

What's more, just search the keyword 'non-editable' in Geyser's code, but no result.So maybe the message is not Geyser send you.

https://github.com/GeyserMC/Geyser/search?q=non-editable&type=

**Comment by DoctorMacc** [comment]
There shouldn't be any results as that would be translated and not in the main repository. That error is likely the server, anyway - apparently this user tried with no plugins and got the error.

**Comment by TheStriker095** [comment]
Can confirm, was tested with no plugins installed. Same result. Error is from server, not geyser or floodgate.

**Comment by bundabrg** [comment]
This error is from CraftBukkit itself.
```java
CraftBukkit/nms-patches/PlayerConnection.patch:                 this.minecraftServer.warning("Player " + this.player.getDisplayName().getString() + " just tried to change non-editable sign");
```

(as an example. Its in other places as well)

**Comment by DoctorMacc** [comment]
I'm unable to confirm this on Paper 128 with iOS nor Xbox. Is it still occuring? Could you provide a dump?

**Comment by zimzaza4** [comment]
I use paper-135, and I have this problem

**Comment by Danielpeter-99** [comment]
Same issue has occurred, it was brought to my attention that it only happens when the user presses enter to make a new line, from that line on everything wont be saved.

**Comment by JH3Y50N** [comment]
i have this problem..

[01:20:37] [Server thread/WARN]: Player Ovo9623 just tried to change non-editable sign

**Comment by Chew** [comment]
If you are having issues please provide your Geyser and server versions (a dump works as well). Just telling us you are having the issue does nothing as we already know this is an issue

**Comment by DoctorMacc** [comment]
Please also provide your Bedrock client version and device; thank you!

**Comment by JH3Y50N** [comment]
> Please also provide your Bedrock client version and device; thank you!

lasted NOT BETA playstore version...

**Comment by j5155** [comment]
> > Please also provide your Bedrock client version and device; thank you!
> 
> lasted NOT BETA playstore version...

Please give us the specific text shown on the Minecraft main menu screen in the bottom right. Also, please give us the model of device you're using (i.e. iPhone 7, Google Pixel 2, Xbox One, etc.)

**Comment by zimzaza4** [comment]
Minecraft 1.16.101
Android
Paper1.16.4
The problem occurred

**Comment by JH3Y50N** [comment]
> > > Please also provide your Bedrock client version and device; thank you!
> > 
> > 
> > lasted NOT BETA playstore version...
> 
> Please give us the specific text shown on the Minecraft main menu screen in the bottom right. Also, please give us the model of device you're using (i.e. iPhone 7, Google Pixel 2, Xbox One, etc.)

![WhatsApp Image 2020-11-28 at 1 12 03 AM](https://user-images.githubusercontent.com/29031972/100494322-68630880-311f-11eb-8def-21e788e6a24f.jpeg)
Samsung A30

**Comment by zimzaza4** [comment]
The problem is still unresolved

**Comment by zimzaza4** [comment]
This is the test result at test.geysermc.org
Input text:
![Screenshot_20210205_151738_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/107001939-7a1ef700-67c5-11eb-88e3-9e9c5c86376f.jpg)
result:
![Screenshot_20210205_151742_com mojang minecraftpe](https://user-images.githubusercontent.com/53421735/107001968-85722280-67c5-11eb-9b96-0fa9825eeb14.jpg)

**Comment by Camotoy** [comment]
Has this error been occurring as of recent?

**Comment by zimzaza4** [comment]
Yes.
I tested it on my server

> Has this error been occurring as of recent?

**Comment by JH3Y50N** [comment]
> Has this error been occurring as of recent?

Yes, i solve the problem... Just change the device keyboard.. use Gboard and fix :D, but it's a Geyser bug dont accept some keyboards..

**Comment by fabegalo** [comment]
Good morning, so I come here to complement what the colleague said above, the same problem occurred when writing on a board on the Minecraft 1.17 server using the latest version of Geyser, a specific player had the problem, I made him install the Gboard keyboard from google and the problem was solved, so yes there is the problem and it occurs on certain types of cell phone keyboards!

**Comment by SamGamerYT** [comment]
Still happening on latest geyser & java version (Java 16)

**Comment by edyangel** [comment]
sigue sucediendo en la ultima version de geyser #898

**Comment by eleksploded** [comment]
Seems to be still present on geyser 924, with the message `22.11 08:43:40 [Server] WARN Player {username} just tried to change non-editable sign` coming from the server using `Paper-358` and waterfall `Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448`. Any help would be appreciated as this prevents BE players from making chest shops.

**Comment by JH3Y50N** [comment]
> Seems to be still present on geyser 924, with the message `22.11 08:43:40 [Server] WARN Player {username} just tried to change non-editable sign` coming from the server using `Paper-358` and waterfall `Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448`. Any help would be appreciated as this prevents BE players from making chest shops.

This is a problem related to the keyboard of the player's device, tell them to use the Gboard (google keyboard) that the problem is solved.

**Comment by rgronberg** [comment]
> > Seems to be still present on geyser 924, with the message `22.11 08:43:40 [Server] WARN Player {username} just tried to change non-editable sign` coming from the server using `Paper-358` and waterfall `Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448`. Any help would be appreciated as this prevents BE players from making chest shops.
> 
> This is a problem related to the keyboard of the player's device, tell them to use the Gboard (google keyboard) that the problem is solved.

This issue effects Nintendo switch too, where it is not possible to use a different keyboard

**Comment by Camotoy** [comment]
OK, I have finally been able to confirm this on at least PS4 with Geyser 3251d9 and Paper 1.18.1 101. Write some text, and then use L1/R1 to move your cursor. This will send an identical sign update packet which breaks our workarounds.

**Comment by starcatmeow** [comment]
Confirmed on Geyser https://github.com/GeyserMC/Geyser/commit/e73a4efe606c4531769f4c045bb6cc20ef061550 , Paper 1.18.1-187, Minecraft Bedrock Android v1.18.2 with Gboard Chinese Pinyin Keyboard. Reproduction steps:
- Place a sign
- Type Chinese characters in the first line
- UNDER Chinese Keyboard press enter
- Type in the second line

Problem seems to be caused by https://github.com/GeyserMC/Geyser/blob/e73a4efe606c4531769f4c045bb6cc20ef061550/core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBlockEntityDataTranslator.java#L50

I printed some log to the console by changing to the following code.

```diff
diff --git a/core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBlockEntityDataTranslator.java b/core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBlockEntityDataTranslator.java
index d00914fb..9a2ec856 100644
--- a/core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBlockEntityDataTranslator.java
+++ b/core/src/main/java/org/geysermc/geyser/translator/protocol/bedrock/BedrockBlockEntityDataTranslator.java
@@ -44,13 +44,17 @@ public class BedrockBlockEntityDataTranslator extends PacketTranslator<BlockEnti
         String id = tag.getString("id");
         if (id.equals("Sign")) {
             String text = tag.getString("Text");
+            System.err.println(tag.toString());
+            System.err.println(text);
             // This is the reason why this all works - Bedrock sends packets every time you update the sign, Java only wants the final packet
             // But Bedrock sends one final packet when you're done editing the sign, which should be equal to the last message since there's no edits
             // So if the latest update does not match the last cached update then it's still being edited
             if (!text.equals(session.getLastSignMessage())) {
                 session.setLastSignMessage(text);
+                System.err.println("not same as before, skip");
                 return;
             }
+            System.err.println("FINAL SUBMIT");
             // Otherwise the two messages are identical and we can get to work deconstructing
             StringBuilder newMessage = new StringBuilder();
             // While Bedrock's sign lines are one string, Java's is an array of each line
@@ -107,6 +111,10 @@ public class BedrockBlockEntityDataTranslator extends PacketTranslator<BlockEnti
             // Put the final line on since it isn't done in the for loop
             if (iterator < lines.length) lines[iterator] = newMessage.toString();
             Position pos = new Position(tag.getInt("x"), tag.getInt("y"), tag.getInt("z"));
+            System.err.println(lines[0]);
+            System.err.println(lines[1]);
+            System.err.println(lines[2]);
+            System.err.println(lines[3]);
             ServerboundSignUpdatePacket signUpdatePacket = new ServerboundSignUpdatePacket(pos, lines);
             session.sendDownstreamPacket(signUpdatePacket);
```

And after pressing enter in Gboard Chinese Keyboard (not exiting the edit GUI), Geyser received two same packet in a row, which lead the code to send the packet to the Java server.

[![asciicast](https://asciinema.org/a/467615.svg)](https://asciinema.org/a/467615)

I guess keyboards in other languages may also cause the bug. Maybe we need to find other ways to determine whether the user really finishes typing(exits the edit GUI).

**Comment by Camotoy** [comment]
This may no longer be an issue with 1.18.30, unless the accidental parity change was a bug.

**Comment by JH3Y50N** [comment]
> This may no longer be an issue with 1.18.30, unless the accidental parity change was a bug.

haha, the problem is black...

**Comment by duarbala** [comment]
> > This may no longer be an issue with 1.18.30, unless the accidental parity change was a bug.
> 
> haha, the problem is black...

really has this bug and from what I've tested it's only version 1.18.30

**Comment by Camotoy** [comment]
As far as I'm aware, this is no longer an issue with 1.18.30, and 1.19 is keeping the behavior that fixes this issue. Let us know if the issue still persists, and on what device/model. Thanks!
