### ISSUE TITLE
Player NPC's going invisible

### ISSUE THREAD

**Issue by DuneSciFye** [GeyserMC/Geyser#3356]
### Describe the bug

When attacking player NPC's disguised with a skin from LibsDisguises, they go invisible after a bit.

### To Reproduce

1. Have a player npc
2. Attack it
3. It should go invisible 

### Expected behaviour

It shouldn't go invisible

### Screenshots / Videos

https://user-images.githubusercontent.com/65089425/196579778-8e341798-91a7-4c36-a377-203163160d37.MOV

https://user-images.githubusercontent.com/65089425/196579864-421dc2bd-fc37-41f9-9134-74fde64a3788.MOV

### Server Version and Plugins

Current: git-Purpur-1799 (MC: 1.19.2)

Plugins (48): AdvancedEnchantments, AntiDrop, AntiPopup, BetterStructures, ChestProtect, ChunkVisualizer, Chunky, CommandWhitelist, ConsoleSpamFix, CoreProtect, DeluxeMenus, DiscordSRV, EliteMobs, Essentials, EssentialsChat, EssentialsSpawn, ExecutableItems, FastAsyncWorldEdit, GSit, GeyserHacks, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, ItemAntiDespawn, ItemDeath, KixsAutoAnnouncerPremium, Lands, LandsDiscordBot, LibsDisguises, LiteBans, LuckPerms, MyCommand, OpenInv, PlaceholderAPI, PocketGames, ProtocolLib, SCore, ServerUtils, TAB, Vault, VentureChat, VentureChatWorkaround, WorldGuard, WorldGuardExtraFlags, dynmap, floodgate and spark

### Geyser Dump

https://dump.geysermc.org/F3ZB8Vsnft9X2vOyYt29ZZZNR1X4wR4d

### Geyser Version

floodgate (2.2.0-SNAPSHOT (b73-4f36112)), Geyser-Velocity (2.1.0-SNAPSHOT (git-master-8beae31)),

**Comment by Tydium** [comment]
I went and inspected this server myself. They are using normal player npcs with skins over them to display these custom gladiators. I joined on pocket edition and when I joined they did show normally at first. However within a minute they all disappeared. This is NOT a resource pack related issue. Just player npcs disappearing. I noticed that normal players themselves do not disappear along with the NPCs. (as far as I could see)

**Comment by Camotoy** [comment]
This is possibly related to #3315.

**Comment by DuneSciFye** [comment]
Probably is, any other information I should provide or testing I should do?

**Comment by onebeastchris** [comment]
This should be fixed on the latest Geyser version, so try updating Geyser

**Comment by callum5771** [comment]
**Sorry to butt in here!** I'm having very similar issues with LibsDisguises / ProtocolLib also, I'm using the recommended versions of both plugins for 1.19.3 Spigot.

After stumbling upon this and reading the above, I updated Geyser to the latest build (both on my Bungee and Spigot end servers) and while the issue has gotten a little better, there's still an issue. It looks like **entity** (cat, wolf .etc) disguises work just fine, but disguising as their "falling block" option breaks things. I've attached a video to this comment showing Java on the left (disguised) and Bedrock on the right, I can see that the 'falling block' appears to fall through the floor (although it's not very clear in this video specifically, but I thought I'd try and show the issue visually - you can see that when my disguise moves, it does not move on Bedrock) - so I thought I'd post this here in case it helps solve the problem.

You can do a mini-test / replication of this in-game by spinning up a server with LibsDisguises and ProtocolLib installed, then by using /disguise Falling_Block

Video of issue: https://youtu.be/JLpJ5eU3s9o

_I hope this helps! Let me know if I can be of any further use in solving this!_

**Comment by RocketManKian** [comment]
I too am having this issue

**Comment by Kas-tle** [comment]
Closing since the comments on this issue since we implemented a fix seemed to be relating to another bug that already has an opened issue.
