### ISSUE TITLE
Invalid Key Bytes

### ISSUE THREAD

**Issue by alexanderdidio** [GeyserMC/Geyser#3849]
### Describe the bug

Still invalid key byte errors that are preventing players from joining my survival server until the affected player in the server is removed. But this time (refer to survival logs below), it kicked players from the spigot server which it never did before.

Velocity: <https://mcpaste.io/8c1c2bb0dd7e841a>
Geyser: <https://mcpaste.io/41b4a51c7624fa23>
Survival: <https://mcpaste.io/337b2568755ab011>

### To Reproduce

N/A

### Expected behaviour

N/A

### Geyser Dump

https://dump.geysermc.org/5hXCIMCP6Prl4q3WbbxErVVWeUp6gxoQ

### Geyser Version

2.1.1-SNAPSHOT (git-DEV-eb825ee)

**Comment by Camotoy** [comment]
The Geyser log errors should be fixed in the next build.

**Comment by Konicai** [comment]
its closed for a reason :p

**Comment by alexanderdidio** [comment]
> 
It was still apparent after running on the dev build that was released after https://github.com/GeyserMC/Geyser/issues/3838 was closed (refer to velocity logs in this issue). However, I've updated to the latest Geyser that @Camotoy just pushed. Will report if anymore issues occur. Thanks for the fast support everyone!

**Comment by alexanderdidio** [comment]
Even after updating geyser this is still happening https://mcpaste.io/ed3701fe62f04bf6

**Comment by Konicai** [comment]
Share geyser logs and dump again please

**Comment by alexanderdidio** [comment]
Reached out to some other large server owners they mentioned removing this listener fixed the issue for them https://github.com/GeyserMC/Floodgate/blob/227858930d98dc8e89054b38edebc3b432c0a5eb/spigot/src/main/java/org/geysermc/floodgate/listener/PaperProfileListener.java#L42-L64

**Comment by alexanderdidio** [comment]
And it's still causing these ViaVersion errors too https://mcpaste.io/7bfff88bda4b04f9

Again, I believe the problem lies within floodgate and not geyser.

**Comment by frogglen** [comment]
still happen in lastest build geyser 176 commit [178829](https://github.com/GeyserMC/Geyser/commit/1788295291c1fc114e0e3c803175ee0b905d3e53)

```
[17:06:25 ERROR]: [server connection] .geoutroll -> survival: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@4d68500a
io.netty.handler.codec.CorruptedFrameException: Error decoding class net.elytrium.limboapi.injection.packet.UpsertPlayerInfoHook Direction CLIENTBOUND Protocol 1.20 State PLAY ID 3a
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:131) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:86) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid key bytes
        at com.velocitypowered.proxy.crypto.EncryptionUtils.parseRsaPublicKey(EncryptionUtils.java:206) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.crypto.IdentifiedKeyImpl.<init>(IdentifiedKeyImpl.java:46) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.ProtocolUtils.readPlayerKey(ProtocolUtils.java:585) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.packet.chat.RemoteChatSession.<init>(RemoteChatSession.java:36) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo$Action.lambda$static$2(UpsertPlayerInfo.java:155) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.packet.UpsertPlayerInfo.decode(UpsertPlayerInfo.java:103) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:84) ~[server.jar:3.2.0-SNAPSHOT (git-5ef90c46-b258)]
        ... 24 more
```

**Comment by alexanderdidio** [comment]
> Reached out to some other large server owners they mentioned removing this listener fixed the issue for them https://github.com/GeyserMC/Floodgate/blob/227858930d98dc8e89054b38edebc3b432c0a5eb/spigot/src/main/java/org/geysermc/floodgate/listener/PaperProfileListener.java#L42-L64

I can confirm that compiling floodgate with this event handler removed fixes the issue.

**Comment by frogglen** [comment]
> > Reached out to some other large server owners they mentioned removing this listener fixed the issue for them https://github.com/GeyserMC/Floodgate/blob/227858930d98dc8e89054b38edebc3b432c0a5eb/spigot/src/main/java/org/geysermc/floodgate/listener/PaperProfileListener.java#L42-L64
> 
> I can confirm that compiling floodgate with this event handler removed fixes the issue.

could you shared please?

**Comment by alexanderdidio** [comment]
> > > Reached out to some other large server owners they mentioned removing this listener fixed the issue for them https://github.com/GeyserMC/Floodgate/blob/227858930d98dc8e89054b38edebc3b432c0a5eb/spigot/src/main/java/org/geysermc/floodgate/listener/PaperProfileListener.java#L42-L64
> > 
> > 
> > I can confirm that compiling floodgate with this event handler removed fixes the issue.
> 
> could you shared please?

What's your discord?

**Comment by frogglen** [comment]
> > > > Reached out to some other large server owners they mentioned removing this listener fixed the issue for them https://github.com/GeyserMC/Floodgate/blob/227858930d98dc8e89054b38edebc3b432c0a5eb/spigot/src/main/java/org/geysermc/floodgate/listener/PaperProfileListener.java#L42-L64
> > > 
> > > 
> > > I can confirm that compiling floodgate with this event handler removed fixes the issue.
> > 
> > 
> > could you shared please?
> 
> What's your discord?

Frog42#1787

**Comment by Tim203** [comment]
And the issue doesn't exist when you only have Floodgate on your proxy?
I currently don't see why that code should trigger an initialize chat player info packet.

**Comment by alexanderdidio** [comment]
> And the issue doesn't exist when you only have Floodgate on your proxy & server? I currently don't see why that code should trigger an initialize chat player info packet.

I run floodgate on velocity and on every spigot server. This issue was persistent until I removed that event handler from floodgate-spigot.

**Comment by frogglen** [comment]
I can confirm that after 7 hours using the floodgate version that alexanderdidio gave me, I have not had any serious problems with massive disconnections of my users.

previously I would not spend more than 2 hours and had constant problems of disconnections and another thing that I have noticed is that now it seems that it is using a larger amount of ram than normal.

**Comment by frogglen** [comment]
maybe this issue should be opened in the floodgate github?

**Comment by onebeastchris** [comment]
https://github.com/GeyserMC/Floodgate/issues/420 closing, as this is a floodgate issue that's being tracked in the linked post - thanks for reporting.
