### ISSUE TITLE
Firework nullptr

### ISSUE THREAD

**Issue by sowhatifimlazy** [GeyserMC/Geyser#628]
**Describe the bug**
Some firework's just don't show up on Bedrock clients and throws this error in the Geyser console:
https://hasteb.in/omadefaf.rb

**To Reproduce**
Create a firework w/ this code:
https://hasteb.in/iyuyofoz.coffeescript

**Expected behavior**
Firework should appear.

**Screenshots / Videos**
Not needed, the firework just doesn't appear on Bedrock clients.

**Server Version**
Tuinity version git-Tuinity-"973b5c7" (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Geyser Version**
Geyser version 1.0-SNAPSHOT (git-master-681cbee)

**Minecraft: Bedrock Edition Version**
iOS v1.14.60

**Additional Context**
n/a

**Comment by RednedEpic** [comment]
Resolved in fe6257bb38c417c78dea9d2e1b229c32443c7b70. Please update your Geyser version.

**Comment by DoctorMacc** [comment]
No, I updated the item translator. This is the entity.

**Comment by RednedEpic** [comment]
> No, I updated the item translator. This is the entity.

Whoops mb.

**Comment by rtm516** [comment]
Can you test this PR https://github.com/GeyserMC/Geyser/pull/633

**Comment by sowhatifimlazy** [comment]
Just tested on: Geyser version 1.0-SNAPSHOT (git-master-7154e1c), still appears to be happening. I'm not to aware of the parity between Bedrock and Java, so maybe I'm using an effect that Bedrock just doesn't have?

**Comment by DoctorMacc** [comment]
@sowhatifimlazy can you send the error you are getting now? It should be a little different from the one you sent before.

**Comment by rtm516** [comment]
Can you share the new error message as it will have likely changed because the line will have moved in the file
