### ISSUE TITLE
Issue with Fireworks [java.lang.Integer cannot be cast to class java.lang.Byte (FireworkEntity)]

### ISSUE THREAD

**Issue by Ashesh3** [GeyserMC/Geyser#679]
**Describe the bug**
I get the following exception in my console whenever i pass near any firework, i do not see the fireworks on bedrock edition. I do see the fireworks on my Java client.

Fireworks launched on bedrock edition -> can see on both bedrock and java clients

Fireworks launched on Java client -> can see on only java client, there are NO effects seen on the bedrock edition

**To Reproduce**
1. Connect both a bedrock player and java player 
2. On java client, give yourself a firework 
`/give @p firework_rocket{Fireworks:{Flight:2,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;11743532]}]}} 1`
3. Now deploy the firework observing it from the bedrock player
4. The firework launches but it never explodes(no explosion effects seen) on (only) the bedrock edition.

**Expected behavior**
Firework effects should be visible on bedrock client the same way they are on java client

**Screenshots / Videos**
Firework Effect on Java client [Launched on Java client]
![image](https://user-images.githubusercontent.com/3626859/83096169-a7f25e80-a0c2-11ea-997e-1281884bc839.png)

Same firework as seen on Bedrock client [Launched on java client]
![image](https://user-images.githubusercontent.com/3626859/83096280-ec7dfa00-a0c2-11ea-82e1-9e865b1b5257.png)

**Server Version**
![image](https://user-images.githubusercontent.com/3626859/83096508-7af27b80-a0c3-11ea-9b3a-97912bc2bc3e.png)

**Geyser Version**
Geyser-Bukkit v1.0-SNAPSHOT
Bukkit plugin
auth-type: offline

**Minecraft: Bedrock Edition Version**
1.14.60.5

**Additional Context**
It does not seem like any plugins would cause the issue. 
I have attached the server console output.
[console.txt](https://github.com/GeyserMC/Geyser/files/4693114/console.txt)

**Comment by rtm516** [comment]
Using the following should fix the issue, its because you specified an int for a byte variable (as per the NBT data here), we should look into fixing this.
```
/give @p firework_rocket{Fireworks:{Flight:2b,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;11743532]}]}} 1
```

**Comment by Ashesh3** [comment]
> ```
> /give @p firework_rocket{Fireworks:{Flight:2b,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;11743532]}]}} 1
> ```

Thank you for the reply but i tried to launch a rocket on java edition 
`/give @p firework_rocket{Fireworks:{Flight:2b,Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[I;11743532]}]}} 1`
using that command,

It does work for me in java client (red explosion effect)

but i see nothing at all on bedrock edition.

Good news: no more exceptions in console
Bad news: still don't see an explosion on bedrock

![image](https://user-images.githubusercontent.com/3626859/83133673-d7c05700-a100-11ea-9d88-a06b41dd9856.png)

![image](https://user-images.githubusercontent.com/3626859/83133691-db53de00-a100-11ea-9761-4a901d6f9278.png)

[images show a rocket launched by the above fixed give command on java client and as seen on bedrock client (the explosion does not show up)]

**Comment by rtm516** [comment]
Try:
```
/give @p firework_rocket{Fireworks:{Flight:2b,Explosions:[{Type:1b,Flicker:0b,Trail:0b,Colors:[I;11743532]}]}} 1
```

**Comment by Ashesh3** [comment]
Oh, seems to be working good, Thank you for the help.

**Comment by Arktisfox** [comment]
I tested this on Spigot, and had no issue spawning it from the server console or a command block. It may be something within Paper.
